- hosts: centos
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache Service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: install the latest version of unzip
    yum:
      name: unzip
      state: latest

  - name: unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page285/gymster.zip 
      dest: /tmp
      remote_src: yes

  - name: Copy content of tmp
    copy:
      src: /tmp/gym-html-template
      dest: /var/www/html/
      remote_src: yes
